// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'execution_types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_execution_svc`

Future<FrbExecutionResult> startExecutionRequest(
        {required FrbStartExecutionRequest req}) =>
    StepflowApi.instance.api.crateFrbApiStartExecutionRequest(req: req);

Future<FrbExecutionResult> getExecutionById({required String runId}) =>
    StepflowApi.instance.api.crateFrbApiGetExecutionById(runId: runId);

Future<List<FrbExecutionResult>> listExecutionsRequest(
        {required FrbListRequest req}) =>
    StepflowApi.instance.api.crateFrbApiListExecutionsRequest(req: req);

Future<void> updateExecutionRequest(
        {required String runId, required FrbExecUpdateRequest req}) =>
    StepflowApi.instance.api
        .crateFrbApiUpdateExecutionRequest(runId: runId, req: req);

Future<void> deleteExecutionRequest({required String runId}) =>
    StepflowApi.instance.api.crateFrbApiDeleteExecutionRequest(runId: runId);

Future<List<FrbExecutionResult>> listExecutionsByStatusRequest(
        {required FrbListByStatusRequest req}) =>
    StepflowApi.instance.api.crateFrbApiListExecutionsByStatusRequest(req: req);
