// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'execution_types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<FrbExecutionResult> startExecution(
        {required FrbStartExecutionRequest req}) =>
    StepflowApi.instance.api.crateFrbApiStartExecution(req: req);

Future<FrbExecutionResult> getExecution({required String runId}) =>
    StepflowApi.instance.api.crateFrbApiGetExecution(runId: runId);

Future<List<FrbExecutionResult>> listExecutions(
        {required FrbListRequest req}) =>
    StepflowApi.instance.api.crateFrbApiListExecutions(req: req);

Future<void> updateExecution(
        {required String runId, required FrbExecUpdateRequest req}) =>
    StepflowApi.instance.api.crateFrbApiUpdateExecution(runId: runId, req: req);

Future<void> deleteExecution({required String runId}) =>
    StepflowApi.instance.api.crateFrbApiDeleteExecution(runId: runId);

Future<List<FrbExecutionResult>> listExecutionsByStatus(
        {required FrbListByStatusRequest req}) =>
    StepflowApi.instance.api.crateFrbApiListExecutionsByStatus(req: req);
