// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'event_bridge.dart';
import 'execution_types.dart';
import 'frb_api.dart';
import 'frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class StepflowApiApiImplPlatform extends BaseApiImpl<StepflowApiWire> {
  StepflowApiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_FrbEventStreamPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FrbEventStream
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          dynamic raw);

  @protected
  FrbEventStream
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  FrbExecUpdateRequest dco_decode_box_autoadd_frb_exec_update_request(
      dynamic raw);

  @protected
  FrbListByStatusRequest dco_decode_box_autoadd_frb_list_by_status_request(
      dynamic raw);

  @protected
  FrbListRequest dco_decode_box_autoadd_frb_list_request(dynamic raw);

  @protected
  FrbStartExecutionRequest dco_decode_box_autoadd_frb_start_execution_request(
      dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  FrbExecUpdateRequest dco_decode_frb_exec_update_request(dynamic raw);

  @protected
  FrbExecutionResult dco_decode_frb_execution_result(dynamic raw);

  @protected
  FrbListByStatusRequest dco_decode_frb_list_by_status_request(dynamic raw);

  @protected
  FrbListRequest dco_decode_frb_list_request(dynamic raw);

  @protected
  FrbStartExecutionRequest dco_decode_frb_start_execution_request(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<FrbExecutionResult> dco_decode_list_frb_execution_result(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  FrbEventStream
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          SseDeserializer deserializer);

  @protected
  FrbEventStream
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  FrbExecUpdateRequest sse_decode_box_autoadd_frb_exec_update_request(
      SseDeserializer deserializer);

  @protected
  FrbListByStatusRequest sse_decode_box_autoadd_frb_list_by_status_request(
      SseDeserializer deserializer);

  @protected
  FrbListRequest sse_decode_box_autoadd_frb_list_request(
      SseDeserializer deserializer);

  @protected
  FrbStartExecutionRequest sse_decode_box_autoadd_frb_start_execution_request(
      SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  FrbExecUpdateRequest sse_decode_frb_exec_update_request(
      SseDeserializer deserializer);

  @protected
  FrbExecutionResult sse_decode_frb_execution_result(
      SseDeserializer deserializer);

  @protected
  FrbListByStatusRequest sse_decode_frb_list_by_status_request(
      SseDeserializer deserializer);

  @protected
  FrbListRequest sse_decode_frb_list_request(SseDeserializer deserializer);

  @protected
  FrbStartExecutionRequest sse_decode_frb_start_execution_request(
      SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<FrbExecutionResult> sse_decode_list_frb_execution_result(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          FrbEventStream self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          FrbEventStream self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frb_exec_update_request(
      FrbExecUpdateRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frb_list_by_status_request(
      FrbListByStatusRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frb_list_request(
      FrbListRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frb_start_execution_request(
      FrbStartExecutionRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_frb_exec_update_request(
      FrbExecUpdateRequest self, SseSerializer serializer);

  @protected
  void sse_encode_frb_execution_result(
      FrbExecutionResult self, SseSerializer serializer);

  @protected
  void sse_encode_frb_list_by_status_request(
      FrbListByStatusRequest self, SseSerializer serializer);

  @protected
  void sse_encode_frb_list_request(
      FrbListRequest self, SseSerializer serializer);

  @protected
  void sse_encode_frb_start_execution_request(
      FrbStartExecutionRequest self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_frb_execution_result(
      List<FrbExecutionResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class StepflowApiWire implements BaseWire {
  StepflowApiWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
              ptr);
}

@JS('wasm_bindgen')
external StepflowApiWasmModule get wasmModule;

@JS()
@anonymous
extension type StepflowApiWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbEventStream(
          int ptr);
}
