// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_dto/frb_execution.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 启动执行
Future<FrbExecDto> startExecution({required FrbExecStart req}) =>
    StepflowApi.instance.api.crateFrbApisExecutionApiStartExecution(req: req);

/// 获取执行详情
Future<FrbExecDto> getExecutionById({required String runId}) =>
    StepflowApi.instance.api
        .crateFrbApisExecutionApiGetExecutionById(runId: runId);

/// 获取执行列表
Future<List<FrbExecDto>> listExecutions({required FrbPage req}) =>
    StepflowApi.instance.api.crateFrbApisExecutionApiListExecutions(req: req);

/// 按状态获取执行列表
Future<List<FrbExecDto>> listExecutionsByStatus({required FrbStatusPage req}) =>
    StepflowApi.instance.api
        .crateFrbApisExecutionApiListExecutionsByStatus(req: req);

/// 更新执行状态
Future<FrbExecDto> updateExecution(
        {required String runId, required FrbExecUpdate req}) =>
    StepflowApi.instance.api
        .crateFrbApisExecutionApiUpdateExecution(runId: runId, req: req);

/// 删除执行
Future<void> deleteExecution({required String runId}) =>
    StepflowApi.instance.api
        .crateFrbApisExecutionApiDeleteExecution(runId: runId);
