// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'frb_engine_event.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

class FrbEventEnvelope {
  final String eventId;
  final String timestamp;
  final String source;
  final FrbEngineEvent payload;

  const FrbEventEnvelope({
    required this.eventId,
    required this.timestamp,
    required this.source,
    required this.payload,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      timestamp.hashCode ^
      source.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbEventEnvelope &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          timestamp == other.timestamp &&
          source == other.source &&
          payload == other.payload;
}
